In [1]:
import pandas as pd

In [3]:
two_cases = pd.read_csv('/home/ubuntu/QA_code/QA_application/Processed_Input_files/2_cases.csv').iloc[:,1:]
two_cases

                                   image  labels
0                     207521_1350712.JPG       0
1                     207521_1350713.JPG       0
2                     207521_1350715.JPG       0
3                     207521_1350716.JPG       0
4                     207521_1350717.JPG       0
...                                  ...     ...
539185   691008_8567632_Left Field 1.JPG       0
539186  691008_8567633_Right Field 2.JPG       0
539187   691008_8567634_Left Field 2.JPG       0
539188  691008_8567635_Right Field 3.JPG       0
539189   691008_8567636_Left Field 3.JPG       0

[539190 rows x 2 columns]

In [4]:
two_cases = two_cases.sample(frac=1, random_state=42)

In [5]:
two_cases

                                     image  labels
462332     806597_9478940_Left Field 3.JPG       0
127227  1323368_13520882_Right Field 1.JPG       0
182816   1270743_13137857_Left Field 1.JPG       0
175071  1264191_13087326_Right Field 3.JPG       0
112267  1316134_13467713_Right Field 3.JPG       0
...                                    ...     ...
110268  1314554_13455839_Right Field 3.JPG       1
259178  1132380_12071324_Right Field 1.JPG       0
365838  1120879_11978828_Right Field 3.JPG       0
131932  1325187_13535058_Right Field 3.JPG       0
121958   1321278_13505627_Left Field 3.JPG       0

[539190 rows x 2 columns]

In [6]:
sfact = int((0.05*len(two_cases))/2)
df_temp_1 = two_cases[two_cases['labels'] == 0][:sfact]
df_temp_2 = two_cases[two_cases['labels'] == 1][:sfact]
df_temp_3 = two_cases[two_cases['labels'] == 2][:sfact]
df_temp_4 = two_cases[two_cases['labels'] == 3][:sfact]

In [7]:
test_df = pd.concat([df_temp_1, df_temp_2, df_temp_3, df_temp_4])

In [8]:
test_y = test_df['labels']

In [14]:
df_train_val = two_cases[~two_cases['image'].isin(test_df['image'])]

In [15]:
df_train_val

                                     image  labels
308763   1057328_11472605_Left Field 3.JPG       0
36805   1334116_13599891_Right Field 1.JPG       0
400093    926652_10417862_Left Field 3.JPG       0
299160   1175273_12410031_Left Field 3.JPG       0
172676  1261963_13070059_Right Field 2.JPG       0
...                                    ...     ...
110268  1314554_13455839_Right Field 3.JPG       1
259178  1132380_12071324_Right Field 1.JPG       0
365838  1120879_11978828_Right Field 3.JPG       0
131932  1325187_13535058_Right Field 3.JPG       0
121958   1321278_13505627_Left Field 3.JPG       0

[512232 rows x 2 columns]

In [16]:
test_df

                                     image  labels
462332     806597_9478940_Left Field 3.JPG       0
127227  1323368_13520882_Right Field 1.JPG       0
182816   1270743_13137857_Left Field 1.JPG       0
175071  1264191_13087326_Right Field 3.JPG       0
112267  1316134_13467713_Right Field 3.JPG       0
...                                    ...     ...
413681   971517_10777032_Right Field 3.JPG       1
27969   1330444_13571434_Right Field 3.JPG       1
509867    628174_8072338_Right Field 2.JPG       1
3873                    304499_2064877.JPG       1
204362  1192373_12544456_Right Field 1.JPG       1

[26958 rows x 2 columns]

In [ ]:
source_files = '/home/ubuntu/EyePacs_Lenke_Dataset'
destination_folder = '/home/ubuntu/EyePacs_Lenke_Dataset_Division/Test'

In [11]:
image_names =list(test_df['image'])

In [12]:
image_names

['806597_9478940_Left Field 3.JPG',
 '1323368_13520882_Right Field 1.JPG',
 '1270743_13137857_Left Field 1.JPG',
 '1264191_13087326_Right Field 3.JPG',
 '1316134_13467713_Right Field 3.JPG',
 '1128783_12043319_Left Field 3.JPG',
 '929062_10436634_Right Field 1.JPG',
 '890218_10130602_Left Field 3.JPG',
 '906489_10260028_Right Field 1.JPG',
 '1275307_13173545_Right Field 1.JPG',
 '908813_10278408_Right Field 1.JPG',
 '1325862_13540191_Left Field 1.JPG',
 '1097357_11792849_Right Field 1.JPG',
 '765575_9157157_Right Field 3.JPG',
 '1200335_12600533_Right Field 3.JPG',
 '796219_9397085_Left Field 2.JPG',
 '1083028_11680874_Right Field 1.JPG',
 '632699_8108140_Left Field 3.JPG',
 '784968_9310479_Right Field 1.JPG',
 '947426_10584092_Left Field 3.JPG',
 '1168198_12353967_Left Field 1.JPG',
 '1195275_12566796_Left Field 3.JPG',
 '1209803_12672711_Left Field 1.JPG',
 '1087650_11716899_Left Field 2.JPG',
 '1341422_13653937_Left Field 3.JPG',
 '1341062_13651400_Left Field 2.JPG',
 '1287563_13268769_Left Field 1.JPG',
 '007-2407-100.JPG',
 '1314608_13456340_Left Field 3.JPG',
 '1340927_13650337_Right Field 3.JPG',
 '1325517_13537346_Right Field 3.JPG',
 '1176342_12418487_Right Field 2.JPG',
 '1323857_13525052_Right Field 2.JPG',
 '1052865_11436693_Right Field 1.JPG',
 '606531_7900864_Right Field 2.JPG',
 '748019_9019497_Right Field 3.JPG',
 '779970_9270855_Right Field 2.JPG',
 '625476_8050853_Right Field 3.JPG',
 '1340074_13644266_Right Field 1.JPG',
 '722986_8828216_Left Field 3.JPG',
 '1149862_12208723_Right Field 3.JPG',
 '1344513_13677194_Right Field 3.JPG',
 '1277360_13189436_Right Field 1.JPG',
 '1343294_13667360_Right Field 3.JPG',
 '1342477_13661648_Right Field 1.JPG',
 '932938_10466565_Left Field 3.JPG',
 '1286397_13259809_Right Field 2.JPG',
 '1195423_12567887_Right Field 3.JPG',
 '1335423_13609572_Right Field 3.JPG',
 '1095131_11775076_Right Field 2.JPG',
 '1096473_11785493_Right Field 3.JPG',
 '1259640_13052170_Right Field 2.JPG',
 '1105134_11853314_Right Field 3.JPG',
 '925914_10411240_Right Field 1.JPG',
 '1329373_13564605_Right Field 1.JPG',
 '1166480_12340320_Left Field 2.JPG',
 '1248188_12966680_Right Field 3.JPG',
 '1089409_11730806_Left Field 3.JPG',
 '623217_8033066_Left Field 2.JPG',
 '1253146_13003712_Right Field 1.JPG',
 '1203428_12623760_Left Field 3.JPG',
 '1152936_12232663_Right Field 3.JPG',
 '1329259_13563707_Right Field 2.JPG',
 '1204010_12628204_Left Field 2.JPG',
 '1152265_12227326_Right Field 2.JPG',
 '1100052_11813666_Left Field 3.JPG',
 '1123383_11999582_Left Field 3.JPG',
 '20170502161755715.JPG',
 '1249907_12979494_Right Field 1.JPG',
 '675313_8442873_Right Field 3.JPG',
 '1177143_12424679_Left Field 3.JPG',
 '1112597_11913293_Right Field 3.JPG',
 '1117886_11954577_Right Field 2.JPG',
 '1268992_13124086_Left Field 3.JPG',
 '1209194_12668039_Left Field 1.JPG',
 '1117322_11949917_Right Field 1.JPG',
 '1272198_13149365_Right Field 2.JPG',
 '1321881_13510071_Left Field 3.JPG',
 '1178298_12433742_Left Field 3.JPG',
 '1213726_12701919_Right Field 3.JPG',
 '1160542_12292858_Right Field 1.JPG',
 '1286192_13258619_Right Field 1.JPG',
 '1066683_11547858_Right Field 3.JPG',
 '1197557_12581264_Left Field 2.JPG',
 '1278071_13194793_Right Field 2.JPG',
 '1217971_12739975_Right Field 2.JPG',
 '1259361_13049974_Right Field 1.JPG',
 '859010_9887384_Right Field 2.JPG',
 '1345351_13682427_Right Field 3.JPG',
 '1150015_12209978_Right Field 2.JPG',
 '1340350_13646266_Right Field 3.JPG',
 '1321991_13510702_Left Field 2.JPG',
 '1143924_12162125_Right Field 3.JPG',
 '862161_9912142_Right Field 3.JPG',
 '849697_9813040_Left Field 2.JPG',
 '1020031_11169895_Right Field 3.JPG',
 '278451_1865443.JPG',
 '1324755_13533591_Left Field 2.JPG',
 '1335484_13609911_Right Field 3.JPG',
 '619227_8001288_Right Field 1.JPG',
 '1071726_11589014_Right Field 1.JPG',
 '674916_8439806_Left Field 2.JPG',
 '686885_8534711_Right Field 1.JPG',
 '1220077_12750002_Right Field 3.JPG',
 '1260835_13061508_Left Field 2.JPG',
 '007-3784-200.JPG',
 '1210188_12675612_Right Field 3.JPG',
 '1161951_12304093_Right Field 3.JPG',
 '1233919_12856797_Right Field 1.JPG',
 '912884_10309246_Left Field 2.JPG',
 '1239968_12904397_Right Field 3.JPG',
 '994165_10961031_Right Field 3.JPG',
 '1235663_12870460_Right Field 3.JPG',
 '1338899_13635446_Right Field 3.JPG',
 '1272903_13154757_Left Field 1.JPG',
 '999357_11003031_Right Field 1.JPG',
 '1313625_13448831_Left Field 2.JPG',
 '1069658_11572168_Left Field 3.JPG',
 '1331883_13581354_Left Field 3.JPG',
 '925369_10406821_Left Field 1.JPG',
 '1107894_11875297_Right Field 3.JPG',
 '1230058_12825943_Left Field 3.JPG',
 '1341488_13654595_Left Field 3.JPG',
 '1333647_13596546_Right Field 3.JPG',
 '1347935_13701235_Left Field 3.JPG',
 '1295835_13313442_Left Field 2.JPG',
 '1097504_11793860_Right Field 3.JPG',
 '1243512_12931152_Left Field 2.JPG',
 '1319214_13490349_Right Field 1.JPG',
 '1204710_12633471_Left Field 1.JPG',
 '1267086_13109182_Right Field 2.JPG',
 '1068809_11565041_Right Field 2.JPG',
 '824616_9620644_Left Field 1.JPG',
 '683828_8510478_Left Field 3.JPG',
 '1228947_12817941_Left Field 1.JPG',
 '1213095_12697153_Right Field 2.JPG',
 '1114867_11931873_Left Field 3.JPG',
 '620743_8013219_Left Field 3.JPG',
 '1178128_12432377_Right Field 3.JPG',
 '1092650_11755297_Right Field 3.JPG',
 '1199548_12594675_Right Field 2.JPG',
 '697624_8620914_Left Field 3.JPG',
 '1140034_12131398_Right Field 1.JPG',
 '616906_7982680_Left Field 2.JPG',
 '1340204_13645337_Right Field 2.JPG',
 '925369_10406816_Right Field 1.JPG',
 '1310143_13422724_Left Field 1.JPG',
 '1324999_13532978_Right Field 3.JPG',
 '974468_10801246_Left Field 3.JPG',
 '830909_9669951_Left Field 2.JPG',
 '1340978_13650689_Right Field 3.JPG',
 '884174_10083474_Right Field 2.JPG',
 '1321620_13507927_Left Field 3.JPG',
 '880447_10054814_Left Field 1.JPG',
 '601550_7862016_Left Field 1.JPG',
 '962589_10705184_Left Field 2.JPG',
 '1113966_11924398_Left Field 3.JPG',
 '1332864_13589546_Right Field 2.JPG',
 '1106041_11860749_Left Field 1.JPG',
 '1028241_11235813_Right Field 3.JPG',
 '1284529_13244827_Left Field 3.JPG',
 '846557_9789186_Right Field 2.JPG',
 '1043269_11359366_Left Field 3.JPG',
 '1207209_12652462_Right Field 3.JPG',
 '771721_9205566_Left Field 1.JPG',
 '630342_8089313_Right Field 1.JPG',
 '633843_8117179_Right Field 1.JPG',
 '1299634_13342132_Left Field 2.JPG',
 '767963_9176150_Left Field 2.JPG',
 '1072390_11594177_Right Field 3.JPG',
 '1326704_13546019_Left Field 3.JPG',
 '1143030_12155128_Left Field 1.JPG',
 '1192444_12545031_Right Field 1.JPG',
 '1267320_13112636_Left Field 1.JPG',
 '1271928_13146984_Right Field 1.JPG',
 '1096882_11788705_Left Field 1.JPG',
 '1178220_12433062_Left Field 2.JPG',
 '734306_8912042_Right Field 3.JPG',
 '1127776_12035205_Left Field 2.JPG',
 '1171806_12382305_Left Field 3.JPG',
 '571341_7624960_Right Field 3.JPG',
 '1344958_13679619_Left Field 2.JPG',
 '1282863_13231576_Right Field 1.JPG',
 '1296729_13320134_Right Field 3.JPG',
 '1320685_13501370_Right Field 2.JPG',
 '20170608143417670.JPG',
 '1333759_13597386_Left Field 3.JPG',
 '689692_8557190_Right Field 2.JPG',
 '1209926_12673642_Right Field 3.JPG',
 '1171830_12382528_Left Field 1.JPG',
 '1109511_11888391_Right Field 1.JPG',
 '1145538_12174607_Left Field 3.JPG',
 '848640_9805113_Left Field 1.JPG',
 '794272_9381837_Right Field 3.JPG',
 '1311900_13435394_Left Field 2.JPG',
 '1046344_11383754_Left Field 3.JPG',
 '845720_9782825_Right Field 2.JPG',
 '1062853_11517417_Left Field 3.JPG',
 '600094_7850575_Left Field 1.JPG',
 '1342910_13664646_Right Field 3.JPG',
 '1244853_12940854_Left Field 3.JPG',
 '1131938_12067886_Right Field 3.JPG',
 '1193539_12553607_Left Field 2.JPG',
 '1115851_11938396_Right Field 1.JPG',
 '1079224_11650339_Right Field 3.JPG',
 '570900_7621657_Left Field 1.JPG',
 '691323_8570118_Left Field 3.JPG',
 '920318_10366997_Right Field 3.JPG',
 '1146545_12182260_Right Field 2.JPG',
 '579811_7691242_Right Field 3.JPG',
 '705473_8682667_Right Field 1.JPG',
 '1301783_13358563_Right Field 2.JPG',
 '810927_9513448_Left Field 2.JPG',
 '1151803_12223725_Left Field 2.JPG',
 '625771_8053262_Left Field 3.JPG',
 '1324478_13529388_Left Field 2.JPG',
 '746860_9010379_Right Field 3.JPG',
 '1228382_12812963_Right Field 2.JPG',
 '1107899_11875334_Left Field 2.JPG',
 '1314783_13457614_Left Field 3.JPG',
 '1311539_13432747_Right Field 3.JPG',
 '1133482_12079782_Left Field 1.JPG',
 '1298350_13332350_Right Field 3.JPG',
 '882401_10069852_Right Field 1.JPG',
 '974124_10798009_Right Field 3.JPG',
 '1158965_12280488_Left Field 1.JPG',
 '660820_8331856_Right Field 1.JPG',
 '1185068_12487155_Left Field 2.JPG',
 '623233_8033233_Left Field 3.JPG',
 '620642_8012276_Right Field 1.JPG',
 '664889_8363690_Right Field 1.JPG',
 '1245053_12942412_Left Field 3.JPG',
 '1335722_13612105_Left Field 2.JPG',
 '1168308_12354827_Left Field 1.JPG',
 '660058_8325797_Left Field 1.JPG',
 '1295349_13310249_Right Field 2.JPG',
 '1202774_12618754_Left Field 2.JPG',
 '1204972_12635505_Left Field 3.JPG',
 '731957_8893862_Left Field 2.JPG',
 '1251137_12988070_Left Field 2.JPG',
 '1318554_13485235_Left Field 1.JPG',
 '592170_7787922_Left Field 1.JPG',
 '1286286_13258970_Left Field 2.JPG',
 '1324963_13532693_Left Field 3.JPG',
 '1174000_12399846_Left Field 3.JPG',
 '631320_8097153_Right Field 1.JPG',
 '1167168_12345816_Left Field 3.JPG',
 '264607_1759326.JPG',
 '1119639_11968805_Left Field 1.JPG',
 '1271347_13142511_Right Field 3.JPG',
 '1270862_13138855_Right Field 1.JPG',
 '1110704_11898031_Left Field 1.JPG',
 '1173460_12395615_Left Field 3.JPG',
 '720557_8803122_Left Field 1.JPG',
 '1339963_13643490_Right Field 3.JPG',
 '1330552_13572194_Right Field 1.JPG',
 '1131191_12062297_Right Field 3.JPG',
 '1082104_11673394_Right Field 1.JPG',
 '1230882_12833076_Right Field 3.JPG',
 '1283598_13237331_Left Field 2.JPG',
 '1093533_11762305_Left Field 3.JPG',
 '1316962_13497105_Left Field 2.JPG',
 '1079853_11655196_Right Field 1.JPG',
 '663579_8353201_Left Field 3.JPG',
 '1017956_11153363_Right Field 3.JPG',
 '1213715_12701986_Left Field 1.JPG',
 '1074197_11609296_Left Field 3.JPG',
 '595202_7811651_Right Field 3.JPG',
 '870080_9973760_Left Field 2.JPG',
 '755776_9080376_Right Field 2.JPG',
 '1228907_12817657_Right Field 1.JPG',
 '572007_7630275_Right Field 3.JPG',
 '1137346_12110020_Left Field 2.JPG',
 '1276716_13184451_Left Field 3.JPG',
 '840906_9747380_Right Field 1.JPG',
 '672970_8424632_Right Field 3.JPG',
 '668662_8393730_Right Field 2.JPG',
 '1138165_12116460_Left Field 3.JPG',
 '1309778_13419978_Left Field 2.JPG',
 '1262835_13076707_Left Field 2.JPG',
 '580629_7697670_Right Field 2.JPG',
 '1184972_12486334_Left Field 1.JPG',
 '1220435_12752668_Right Field 2.JPG',
 '1209668_12671722_Left Field 1.JPG',
 '1253783_13008313_Right Field 1.JPG',
 '1192127_12542581_Left Field 1.JPG',
 '1154958_12249114_Right Field 3.JPG',
 '1286815_13262910_Right Field 1.JPG',
 '1093103_11759086_Left Field 1.JPG',
 '1339400_13639240_Left Field 3.JPG',
 '1135048_12092579_Right Field 3.JPG',
 '654542_8281923_Right Field 2.JPG',
 '935539_10486573_Left Field 1.JPG',
 '731488_8890197_Left Field 3.JPG',
 '1255157_13018481_Right Field 3.JPG',
 '919843_10363180_Left Field 3.JPG',
 '1347580_13698982_Left Field 1.JPG',
 '1342748_13663690_Left Field 1.JPG',
 '226591_1489389.JPG',
 '1180152_12448047_Right Field 2.JPG',
 '1240846_12910990_Right Field 2.JPG',
 '929547_10440146_Right Field 3.JPG',
 '1324744_13531140_Right Field 3.JPG',
 '1315098_13460029_Right Field 3.JPG',
 '902478_10228211_Left Field 2.JPG',
 '1208099_12659687_Right Field 2.JPG',
 '1243930_12933788_Left Field 3.JPG',
 '1166648_12341647_Left Field 2.JPG',
 '1345375_13682633_Left Field 3.JPG',
 '1294179_13300511_Right Field 3.JPG',
 '789363_9343397_Left Field 1.JPG',
 '1341164_13654392_Left Field 2.JPG',
 '858489_9882770_Right Field 3.JPG',
 '988052_10910621_Right Field 2.JPG',
 '1297257_13324303_Left Field 1.JPG',
 '942039_10541235_Left Field 3.JPG',
 '1200864_12609008_Left Field 1.JPG',
 '1344804_13678517_Right Field 2.JPG',
 '662198_8342339_Left Field 1.JPG',
 '1323772_13524382_Right Field 2.JPG',
 '1223165_12773733_Left Field 3.JPG',
 '1314563_13455930_Right Field 2.JPG',
 '669361_8399235_Right Field 1.JPG',
 '762855_9135656_Left Field 3.JPG',
 '1127106_12029633_Left Field 1.JPG',
 '1011595_11101958_Right Field 3.JPG',
 '1252278_12997083_Right Field 1.JPG',
 '1185866_12493351_Right Field 2.JPG',
 '851795_9829199_Left Field 3.JPG',
 '1235957_12872491_Left Field 2.JPG',
 '1311894_13435301_Right Field 1.JPG',
 '1120260_11973974_Right Field 1.JPG',
 '1299460_13340902_Left Field 3.JPG',
 '687479_8539322_Right Field 1.JPG',
 '1295039_13307009_Left Field 1.JPG',
 '1145224_12172172_Left Field 1.JPG',
 '1205557_12639850_Left Field 3.JPG',
 '1069658_11572164_Right Field 3.JPG',
 '942574_10545576_Right Field 3.JPG',
 '1335538_13610376_Right Field 2.JPG',
 '1133360_12078776_Right Field 3.JPG',
 '829100_9656064_Right Field 1.JPG',
 '1337398_13624055_Left Field 2.JPG',
 '1298294_13332055_Left Field 2.JPG',
 '1337574_13625419_Right Field 3.JPG',
 '1280493_13213131_Right Field 3.JPG',
 '823372_9610569_Right Field 1.JPG',
 '1160546_12292832_Left Field 3.JPG',
 '1230472_12828957_Left Field 2.JPG',
 '1341413_13653850_Left Field 1.JPG',
 '606729_7902378_Left Field 3.JPG',
 '1220424_12752616_Right Field 3.JPG',
 '1244792_12940713_Right Field 2.JPG',
 '1340255_13645626_Right Field 1.JPG',
 '1127052_12029212_Left Field 1.JPG',
 '775630_9236576_Right Field 2.JPG',
 '758073_9097908_Right Field 1.JPG',
 '20170618221747607.JPG',
 '1304885_13382344_Left Field 1.JPG',
 '1136420_12102677_Left Field 1.JPG',
 '1179414_12442366_Left Field 2.JPG',
 '602140_7866510_Right Field 2.JPG',
 '642973_8189825_Right Field 1.JPG',
 '634216_8120068_Left Field 2.JPG',
 '755894_9081489_Right Field 3.JPG',
 '1341608_13655263_Left Field 3.JPG',
 '944850_10563592_Right Field 3.JPG',
 '673078_8425248_Left Field 3.JPG',
 '664631_8361579_Right Field 2.JPG',
 '995187_10969187_Left Field 2.JPG',
 '1334945_13605871_Right Field 1.JPG',
 '20170627160330003.JPG',
 '1320059_13496661_Left Field 2.JPG',
 '1220016_12749671_Left Field 3.JPG',
 '861826_9909452_Left Field 1.JPG',
 '1347545_13698665_Right Field 3.JPG',
 '1198467_12587471_Left Field 1.JPG',
 '20170609095102337.JPG',
 '1243905_12933605_Left Field 1.JPG',
 '640405_8169341_Left Field 3.JPG',
 '915708_10330984_Right Field 1.JPG',
 '1222510_12768669_Left Field 1.JPG',
 '1117199_11949135_Left Field 3.JPG',
 '1208785_12665111_Left Field 3.JPG',
 '1093947_11766050_Left Field 3.JPG',
 '1319901_13495418_Right Field 2.JPG',
 '1342833_13664135_Left Field 1.JPG',
 '1158144_12273719_Right Field 1.JPG',
 '933502_10535577_Right Field 2.JPG',
 '1135010_12091586_Left Field 3.JPG',
 '1261618_13067536_Right Field 2.JPG',
 '1082061_11673017_Right Field 1.JPG',
 '1344577_13676774_Right Field 1.JPG',
 '746241_9005545_Right Field 1.JPG',
 '1339884_13642896_Left Field 3.JPG',
 '1203248_12622417_Left Field 2.JPG',
 '1281358_13219771_Right Field 2.JPG',
 '625983_8054803_Left Field 1.JPG',
 '1202837_12619227_Left Field 3.JPG',
 '909336_10282026_Right Field 2.JPG',
 '567037_7591710_Left Field 2.JPG',
 '1333586_13596085_Left Field 2.JPG',
 '1101916_11828216_Left Field 3.JPG',
 '1177570_12427875_Left Field 1.JPG',
 '941919_10540241_Left Field 3.JPG',
 '1269553_13128527_Left Field 2.JPG',
 '1209779_12672510_Right Field 1.JPG',
 '1187081_12502950_Right Field 2.JPG',
 '1182316_12464732_Left Field 2.JPG',
 '1135550_12095785_Right Field 2.JPG',
 '1246220_12951489_Right Field 3.JPG',
 '1334469_13602447_Right Field 2.JPG',
 '1260842_13061548_Right Field 3.JPG',
 '1260219_13056302_Right Field 3.JPG',
 '1343946_13672424_Left Field 1.JPG',
 '593708_7800003_Right Field 1.JPG',
 '1339380_13639059_Right Field 2.JPG',
 '1072272_11593349_Left Field 3.JPG',
 '1285353_13251251_Right Field 3.JPG',
 '1122016_11988401_Right Field 3.JPG',
 '1302200_13361987_Left Field 2.JPG',
 '590233_7772702_Left Field 3.JPG',
 '571257_7624259_Right Field 3.JPG',
 '1263511_13081935_Right Field 2.JPG',
 '695637_8604461_Right Field 3.JPG',
 '769095_9185093_Left Field 2.JPG',
 '898012_10194954_Left Field 1.JPG',
 '620564_8011953_Right Field 1.JPG',
 '1119331_11966471_Left Field 3.JPG',
 '1329275_13563832_Left Field 1.JPG',
 '1228977_12818192_Right Field 2.JPG',
 '1341987_13682100_Left Field 2.JPG',
 '1125361_12015652_Left Field 1.JPG',
 '1347612_13699182_Right Field 3.JPG',
 '1340189_13645048_Right Field 2.JPG',
 '20170222151853159.JPG',
 '1219981_12749464_Right Field 3.JPG',
 '1108587_11880765_Left Field 3.JPG',
 '1333363_13594104_Left Field 2.JPG',
 '1097383_11792595_Right Field 1.JPG',
 '1257539_13036448_Right Field 1.JPG',
 '905324_10250536_Left Field 3.JPG',
 '1343664_13670257_Right Field 3.JPG',
 '1313552_13448256_Right Field 3.JPG',
 '1100958_11820811_Right Field 3.JPG',
 '1254355_13012464_Left Field 3.JPG',
 '1257057_13032951_Left Field 3.JPG',
 '1170399_12371316_Left Field 3.JPG',
 '1223362_12775302_Left Field 1.JPG',
 '1251855_12993742_Left Field 2.JPG',
 '1302406_13363854_Right Field 3.JPG',
 '1321915_13510275_Right Field 3.JPG',
 '1280783_13215475_Left Field 2.JPG',
 '721446_8810033_Left Field 3.JPG',
 '890336134452_698.JPG',
 '1119170_11965030_Left Field 1.JPG',
 '1064832_11533253_Left Field 2.JPG',
 '1270746_13137888_Right Field 1.JPG',
 '1288073_13273066_Left Field 2.JPG',
 '1347914_13701068_Right Field 3.JPG',
 '1150222_12211535_Right Field 3.JPG',
 '1325223_13535560_Left Field 3.JPG',
 '1221544_12761474_Right Field 3.JPG',
 '1309772_13419912_Left Field 1.JPG',
 '1095885_11780985_Left Field 1.JPG',
 '1107631_11873069_Left Field 3.JPG',
 '1330128_13569762_Left Field 1.JPG',
 '1174450_12403441_Left Field 2.JPG',
 '639755_8164674_Right Field 2.JPG',
 '1306729_13396720_Left Field 2.JPG',
 '1205911_12642343_Left Field 3.JPG',
 '1237932_12888226_Right Field 3.JPG',
 '792590_9368751_Right Field 3.JPG',
 '1057946_11477692_Right Field 3.JPG',
 '1131996_12068295_Left Field 2.JPG',
 '1083265_11682715_Right Field 3.JPG',
 '910340_10289813_Left Field 3.JPG',
 '1218380_12737204_Left Field 3.JPG',
 '709655_8715799_Right Field 2.JPG',
 '1184822_12485143_Right Field 2.JPG',
 '1224255_12782229_Left Field 3.JPG',
 '1019404_11165045_Left Field 2.JPG',
 '1340209_13645212_Left Field 2.JPG',
 '675836_8447233_Left Field 2.JPG',
 '1334225_13600813_Left Field 1.JPG',
 '1092013_11750726_Left Field 2.JPG',
 '743050_8980477_Right Field 2.JPG',
 '1110604_11897206_Right Field 1.JPG',
 '1285754_13254469_Right Field 1.JPG',
 '1173401_12395048_Right Field 1.JPG',
 '650227_8247892_Right Field 1.JPG',
 '1238880_12895680_Right Field 1.JPG',
 '1322232_13512425_Right Field 3.JPG',
 '1190692_12531123_Left Field 2.JPG',
 '1275269_13173247_Left Field 1.JPG',
 '1270168_13135232_Left Field 3.JPG',
 '1289206_13281734_Right Field 2.JPG',
 '1328286_13556904_Right Field 3.JPG',
 '672127_8417530_Right Field 1.JPG',
 '1185474_12490259_Left Field 2.JPG',
 '1139356_12126098_Left Field 3.JPG',
 '1188473_12514819_Left Field 2.JPG',
 '1278273_13196387_Right Field 2.JPG',
 '682165_8497418_Left Field 2.JPG',
 '1110874_11899446_Right Field 1.JPG',
 '1252320_12997586_Right Field 3.JPG',
 '1223326_12775078_Right Field 2.JPG',
 '1339021_13636587_Right Field 3.JPG',
 '1179142_12440440_Right Field 2.JPG',
 '1191664_12538630_Left Field 2.JPG',
 '1070653_11580452_Right Field 3.JPG',
 '20170408000114812.JPG',
 '578937_7684513_Left Field 3.JPG',
 '1308524_13410879_Left Field 3.JPG',
 '579439_7688368_Right Field 3.JPG',
 '776694_9244908_Left Field 2.JPG',
 '665829_8371069_Left Field 2.JPG',
 '665257_8366585_Left Field 2.JPG',
 '007-6412-400.JPG',
 '1188584_12514569_Right Field 2.JPG',
 '1271028_13140081_Left Field 3.JPG',
 '1044720_11371043_Left Field 3.JPG',
 '1214855_12710678_Left Field 3.JPG',
 '1069428_11570297_Right Field 3.JPG',
 '1174903_12407092_Left Field 2.JPG',
 '1252890_13001704_Right Field 3.JPG',
 '1198573_12588263_Left Field 1.JPG',
 '989582_10923341_Left Field 2.JPG',
 '1128226_12038858_Left Field 2.JPG',
 '1218595_12738961_Right Field 2.JPG',
 '962341_10703599_Right Field 1.JPG',

In [ ]:
import os, shutil
for image in image_names:
    if(os.path.isfile(os.join(image,source_files))):
        shutil.move(os.join(source_files, image), destination_folder)

In [ ]:
import time
df_train_val.to_csv("/home/ubuntu/QA_code/QA_application/Train_Dev_Test_Split/df_val_{0}.csv".format(timestr))
test_df.to_csv("/home/ubuntu/QA_code/QA_application/Train_Dev_Test_Split/df_val_{0}.csv".format(timestr))

In [3]:
path = '/home/ubuntu/QA_code/QA_application/Train_Dev_Test_Split/df_test_20220728-204321.csv'
test_file = pd.read_csv(path).iloc[:,1:]
test_file

                                    image  labels
0         806597_9478940_Left Field 3.JPG       0
1      1323368_13520882_Right Field 1.JPG       0
2       1270743_13137857_Left Field 1.JPG       0
3      1264191_13087326_Right Field 3.JPG       0
4      1316134_13467713_Right Field 3.JPG       0
...                                   ...     ...
26953   971517_10777032_Right Field 3.JPG       1
26954  1330444_13571434_Right Field 3.JPG       1
26955    628174_8072338_Right Field 2.JPG       1
26956                  304499_2064877.JPG       1
26957  1192373_12544456_Right Field 1.JPG       1

[26958 rows x 2 columns]

In [4]:
path2 = '/home/ubuntu/QA_code/QA_application/Train_Dev_Test_Split/df_test_20220728-185549.csv'
test_file2 = pd.read_csv(path2).iloc[:,1:]
test_file2

                                    image  labels
0         806597_9478940_Left Field 3.JPG       0
1      1323368_13520882_Right Field 1.JPG       0
2       1270743_13137857_Left Field 1.JPG       0
3      1264191_13087326_Right Field 3.JPG       0
4      1316134_13467713_Right Field 3.JPG       0
...                                   ...     ...
26953   971517_10777032_Right Field 3.JPG       1
26954  1330444_13571434_Right Field 3.JPG       1
26955    628174_8072338_Right Field 2.JPG       1
26956                  304499_2064877.JPG       1
26957  1192373_12544456_Right Field 1.JPG       1

[26958 rows x 2 columns]

In [7]:
path3 = '/home/ubuntu/QA_code/QA_application/Train_Dev_Test_Split/df_train_20220728-204321.csv'
train_file3 = pd.read_csv(path3).iloc[:,1:]
train_file3

                                     image  labels
0        1057328_11472605_Left Field 3.JPG       0
1       1334116_13599891_Right Field 1.JPG       0
2         926652_10417862_Left Field 3.JPG       0
3        1175273_12410031_Left Field 3.JPG       0
4       1261963_13070059_Right Field 2.JPG       0
...                                    ...     ...
486617   1341083_13651521_Left Field 3.JPG       0
486618  1132380_12071324_Right Field 1.JPG       0
486619  1120879_11978828_Right Field 3.JPG       0
486620  1325187_13535058_Right Field 3.JPG       0
486621   1321278_13505627_Left Field 3.JPG       0

[486622 rows x 2 columns]

In [8]:
path4 = '/home/ubuntu/QA_code/QA_application/Train_Dev_Test_Split/df_train_20220728-185548.csv'
train_file4 = pd.read_csv(path4).iloc[:,1:]
train_file4

                                     image  labels
0        1057328_11472605_Left Field 3.JPG       0
1       1334116_13599891_Right Field 1.JPG       0
2         926652_10417862_Left Field 3.JPG       0
3        1175273_12410031_Left Field 3.JPG       0
4       1261963_13070059_Right Field 2.JPG       0
...                                    ...     ...
486617   1341083_13651521_Left Field 3.JPG       0
486618  1132380_12071324_Right Field 1.JPG       0
486619  1120879_11978828_Right Field 3.JPG       0
486620  1325187_13535058_Right Field 3.JPG       0
486621   1321278_13505627_Left Field 3.JPG       0

[486622 rows x 2 columns]

In [9]:
train_file4['labels'].value_counts()

0    472749
1     13873
Name: labels, dtype: int64

In [10]:
path4 = '/home/ubuntu/QA_code/QA_application/Train_Dev_Test_Split/df_val_20220728-204321.csv'
val_file4 = pd.read_csv(path4).iloc[:,1:]
val_file4

                                    image  labels
0       1130555_12057130_Left Field 1.JPG       0
1       1077718_11638323_Left Field 1.JPG       0
2       1231503_12837575_Left Field 3.JPG       0
3      1049303_11407460_Right Field 3.JPG       0
4       1188675_12515478_Left Field 3.JPG       0
...                                   ...     ...
25605  1218943_12741729_Right Field 3.JPG       1
25606    790702_9353569_Right Field 1.JPG       1
25607    575290_7656025_Right Field 2.JPG       1
25608   943755_10554932_Right Field 3.JPG       1
25609   952979_10633310_Right Field 2.JPG       1

[25610 rows x 2 columns]

In [11]:
check = pd.read_csv('/home/ubuntu/QA_code/QA_application/Processed_Input_files/Split_folders/2_cases_train_val_20220727-181159.csv').iloc[:,1:]
check

                                     image  labels
0        1057328_11472605_Left Field 3.JPG       0
1       1334116_13599891_Right Field 1.JPG       0
2         926652_10417862_Left Field 3.JPG       0
3        1175273_12410031_Left Field 3.JPG       0
4       1261963_13070059_Right Field 2.JPG       0
...                                    ...     ...
512227  1314554_13455839_Right Field 3.JPG       1
512228  1132380_12071324_Right Field 1.JPG       0
512229  1120879_11978828_Right Field 3.JPG       0
512230  1325187_13535058_Right Field 3.JPG       0
512231   1321278_13505627_Left Field 3.JPG       0

[512232 rows x 2 columns]

In [40]:
import math
sfact = math.floor((0.05262788*len(check))/2)+1
sfact

13479

In [41]:
df_temp_1 = check[check['labels'] == 0][:sfact]
df_temp_2 = check[check['labels'] == 1][:sfact]
test_df = pd.concat([df_temp_1, df_temp_2])

In [42]:
test_df

                                     image  labels
0        1057328_11472605_Left Field 3.JPG       0
1       1334116_13599891_Right Field 1.JPG       0
2         926652_10417862_Left Field 3.JPG       0
3        1175273_12410031_Left Field 3.JPG       0
4       1261963_13070059_Right Field 2.JPG       0
...                                    ...     ...
334849   1277029_13186877_Left Field 2.JPG       1
334850   1281741_13223090_Left Field 2.JPG       1
334860    662755_8346687_Right Field 2.JPG       1
334868  1245682_12947474_Right Field 3.JPG       1
334874  1010730_11095072_Right Field 1.JPG       1

[26958 rows x 2 columns]